name: projeto_estoque
description: Uma breve descrição do seu aplicativo

environment:
  sdk: ">=3.5.0 <4.0.0"  # Certifique-se de que a versão do SDK está correta.

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5

dev_dependencies:
  mockito: ^5.3.2
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0  # Se não tiver, adicione essa linha para o lint
  flutter_test:
    sdk: flutter
  test: ^1.24.0