// Mocks generated by Mockito 5.4.4 from annotations
// in projeto_estoque/test/services/api_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:projeto_estoque/models/car.dart' as _i2;
import 'package:projeto_estoque/models/category.dart' as _i6;
import 'package:projeto_estoque/services/api_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCar_0 extends _i1.SmartFake implements _i2.Car {
  _FakeCar_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i5.Future<List<_i2.Car>> getCars() => (super.noSuchMethod(
        Invocation.method(
          #getCars,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Car>>.value(<_i2.Car>[]),
      ) as _i5.Future<List<_i2.Car>>);

  @override
  _i5.Future<_i2.Car> createCar(_i2.Car? car) => (super.noSuchMethod(
        Invocation.method(
          #createCar,
          [car],
        ),
        returnValue: _i5.Future<_i2.Car>.value(_FakeCar_0(
          this,
          Invocation.method(
            #createCar,
            [car],
          ),
        )),
      ) as _i5.Future<_i2.Car>);

  @override
  _i5.Future<_i2.Car> updateCar(_i2.Car? car) => (super.noSuchMethod(
        Invocation.method(
          #updateCar,
          [car],
        ),
        returnValue: _i5.Future<_i2.Car>.value(_FakeCar_0(
          this,
          Invocation.method(
            #updateCar,
            [car],
          ),
        )),
      ) as _i5.Future<_i2.Car>);

  @override
  _i5.Future<void> deleteCar(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCar,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.Category>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i5.Future<List<_i6.Category>>.value(<_i6.Category>[]),
      ) as _i5.Future<List<_i6.Category>>);
}
